import '../../../core/content/models.dart';

const _englishTopics = <String, String>{
  'legacy_1': 'Light and fire',
  'legacy_2': 'Mosquito',
  'legacy_3': 'Hardened hearts',
  'legacy_4': 'Blind following',
  'legacy_5': 'Charity',
  'legacy_6': 'Insincere charity',
  'legacy_7': 'Fruitful charity',
  'legacy_8': 'Lost harvest',
  'legacy_9': 'Riba',
  'legacy_10': 'Camel and needle',
  'legacy_11': 'Desire',
  'legacy_12': 'Worldly life',
  'legacy_13': 'Ashes',
  'legacy_14': 'Good word',
  'legacy_15': 'Evil word',
  'legacy_16': 'Slavery',
  'legacy_17': 'Helplessness',
  'legacy_18': 'Broken promises',
  'legacy_19': 'Worldly life',
  'legacy_20': 'The fly',
  'legacy_21': 'The spider',
  'legacy_22': 'Ownership',
  'legacy_23': 'Reflection',
  'legacy_24': 'Believers',
  'legacy_25': 'Worldly life',
  'legacy_26': 'The mountain',
  'legacy_27': 'Betrayal',
  'legacy_28': 'Faith',
  'legacy_29': 'Water',
  'text_2_19_20': 'Rainstorm',
  'text_13_17': 'Truth and falsehood',
  'text_22_31': 'Falling from faith',
  'text_24_35': 'Divine light',
  'text_24_39': 'Mirage',
  'text_24_40': 'Deep darkness',
  'text_39_29': 'Conflicting masters',
  'text_48_29': 'Growing faith',
  'text_62_5': 'Unused knowledge',
};

const _urduTopics = <String, String>{
  'legacy_1': 'روشنی اور آگ',
  'legacy_2': 'مچھر',
  'legacy_3': 'سخت دل',
  'legacy_4': 'اندھی تقلید',
  'legacy_5': 'صدقہ',
  'legacy_6': 'ریاکاری',
  'legacy_7': 'بامقصد صدقہ',
  'legacy_8': 'تباہ فصل',
  'legacy_9': 'سود',
  'legacy_10': 'اونٹ اور سوئی',
  'legacy_11': 'خواہش',
  'legacy_12': 'دنیاوی زندگی',
  'legacy_13': 'راکھ',
  'legacy_14': 'اچھی بات',
  'legacy_15': 'بری بات',
  'legacy_16': 'غلامی',
  'legacy_17': 'بے بسی',
  'legacy_18': 'عہد شکنی',
  'legacy_19': 'دنیاوی زندگی',
  'legacy_20': 'مکھی',
  'legacy_21': 'مکڑی',
  'legacy_22': 'ملکیت',
  'legacy_23': 'غور و فکر',
  'legacy_24': 'اہل ایمان',
  'legacy_25': 'دنیاوی زندگی',
  'legacy_26': 'پہاڑ',
  'legacy_27': 'خیانت',
  'legacy_28': 'ایمان',
  'legacy_29': 'پانی',
  'text_2_19_20': 'طوفانی بارش',
  'text_13_17': 'حق اور باطل',
  'text_22_31': 'ایمان سے گرنا',
  'text_24_35': 'نورِ الٰہی',
  'text_24_39': 'سراب',
  'text_24_40': 'گہری تاریکی',
  'text_39_29': 'متعدد آقا',
  'text_48_29': 'بڑھتا ایمان',
  'text_62_5': 'بے عمل علم',
};

const _arabicTopics = <String, String>{
  'legacy_1': 'النور والنار',
  'legacy_2': 'البعوضة',
  'legacy_3': 'قسوة القلوب',
  'legacy_4': 'التقليد الأعمى',
  'legacy_5': 'الصدقة',
  'legacy_6': 'الرياء',
  'legacy_7': 'الصدقة المثمرة',
  'legacy_8': 'الحصاد الضائع',
  'legacy_9': 'الربا',
  'legacy_10': 'الجمل والإبرة',
  'legacy_11': 'الهوى',
  'legacy_12': 'الحياة الدنيا',
  'legacy_13': 'الرماد',
  'legacy_14': 'الكلمة الطيبة',
  'legacy_15': 'الكلمة الخبيثة',
  'legacy_16': 'العبودية',
  'legacy_17': 'العجز',
  'legacy_18': 'نقض العهد',
  'legacy_19': 'الحياة الدنيا',
  'legacy_20': 'الذباب',
  'legacy_21': 'العنكبوت',
  'legacy_22': 'الملكية',
  'legacy_23': 'التدبر',
  'legacy_24': 'المؤمنون',
  'legacy_25': 'الحياة الدنيا',
  'legacy_26': 'الجبل',
  'legacy_27': 'الخيانة',
  'legacy_28': 'الإيمان',
  'legacy_29': 'الماء',
  'text_2_19_20': 'عاصفة ممطرة',
  'text_13_17': 'الحق والباطل',
  'text_22_31': 'السقوط من الإيمان',
  'text_24_35': 'النور الإلهي',
  'text_24_39': 'السراب',
  'text_24_40': 'ظلمات عميقة',
  'text_39_29': 'شركاء متشاكسون',
  'text_48_29': 'نمو الإيمان',
  'text_62_5': 'العلم بلا عمل',
};

const _russianTopics = <String, String>{
  'legacy_1': 'Свет и огонь',
  'legacy_2': 'Комар',
  'legacy_3': 'Ожесточённые сердца',
  'legacy_4': 'Слепое следование',
  'legacy_5': 'Милостыня',
  'legacy_6': 'Неискренняя милостыня',
  'legacy_7': 'Плодотворная милостыня',
  'legacy_8': 'Погибший урожай',
  'legacy_9': 'Риба',
  'legacy_10': 'Верблюд и игольное ушко',
  'legacy_11': 'Страсти',
  'legacy_12': 'Мирская жизнь',
  'legacy_13': 'Пепел',
  'legacy_14': 'Доброе слово',
  'legacy_15': 'Дурное слово',
  'legacy_16': 'Рабство',
  'legacy_17': 'Беспомощность',
  'legacy_18': 'Нарушение обещаний',
  'legacy_19': 'Мирская жизнь',
  'legacy_20': 'Муха',
  'legacy_21': 'Паук',
  'legacy_22': 'Владение',
  'legacy_23': 'Размышление',
  'legacy_24': 'Верующие',
  'legacy_25': 'Мирская жизнь',
  'legacy_26': 'Гора',
  'legacy_27': 'Предательство',
  'legacy_28': 'Вера',
  'legacy_29': 'Вода',
  'text_2_19_20': 'Гроза',
  'text_13_17': 'Истина и ложь',
  'text_22_31': 'Падение от веры',
  'text_24_35': 'Божественный свет',
  'text_24_39': 'Мираж',
  'text_24_40': 'Глубокая тьма',
  'text_39_29': 'Спорящие хозяева',
  'text_48_29': 'Растущая вера',
  'text_62_5': 'Знание без дела'
};
const _chineseTopics = <String, String>{
  'legacy_1': '光与火',
  'legacy_2': '蚊子',
  'legacy_3': '心如坚石',
  'legacy_4': '盲从',
  'legacy_5': '施舍',
  'legacy_6': '虚伪的施舍',
  'legacy_7': '有益的施舍',
  'legacy_8': '毁掉的收成',
  'legacy_9': '利巴（高利贷）',
  'legacy_10': '骆驼与针眼',
  'legacy_11': '私欲',
  'legacy_12': '今世生活',
  'legacy_13': '灰烬',
  'legacy_14': '善言',
  'legacy_15': '恶言',
  'legacy_16': '奴役',
  'legacy_17': '无能为力',
  'legacy_18': '背弃盟约',
  'legacy_19': '今世生活',
  'legacy_20': '苍蝇',
  'legacy_21': '蜘蛛',
  'legacy_22': '所有权',
  'legacy_23': '深思',
  'legacy_24': '信士',
  'legacy_25': '今世生活',
  'legacy_26': '山岳',
  'legacy_27': '背叛',
  'legacy_28': '信仰',
  'legacy_29': '水',
  'text_2_19_20': '暴雨',
  'text_13_17': '真理与虚妄',
  'text_22_31': '失去信仰',
  'text_24_35': '真主之光',
  'text_24_39': '海市蜃楼',
  'text_24_40': '重重黑暗',
  'text_39_29': '相争的主人',
  'text_48_29': '成长的信仰',
  'text_62_5': '知而不行'
};
String exampleTopic(QuranExample example, String languageCode) {
  final topics = switch (languageCode) {
    'ar' => _arabicTopics,
    'ur' => _urduTopics,
    'ru' => _russianTopics,
    'zh' => _chineseTopics,
    _ => _englishTopics
  };
  return topics[example.id] ??
      _englishTopics[example.id] ??
      example.title ??
      example.id;
}
